# Autogenerated wrapper script for PDFHighlights_jll for i686-linux-musl
export PDFHighlightsWrapper

using Poppler_jll
JLLWrappers.@generate_wrapper_header("PDFHighlights")
JLLWrappers.@declare_library_product(PDFHighlightsWrapper, "PDFHighlightsWrapper.so")
function __init__()
    JLLWrappers.@generate_init_header(Poppler_jll)
    JLLWrappers.@init_library_product(
        PDFHighlightsWrapper,
        "lib/PDFHighlightsWrapper.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
