# Autogenerated wrapper script for PDFHighlights_jll for x86_64-w64-mingw32
export PDFHighlightsWrapper

using Poppler_jll
JLLWrappers.@generate_wrapper_header("PDFHighlights")
JLLWrappers.@declare_library_product(PDFHighlightsWrapper, "PDFHighlightsWrapper.dll")
function __init__()
    JLLWrappers.@generate_init_header(Poppler_jll)
    JLLWrappers.@init_library_product(
        PDFHighlightsWrapper,
        "bin\\PDFHighlightsWrapper.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
